// <auto-generated />
namespace PublicSafety.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_MatrixItem_toIssuances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_MatrixItem_toIssuances));
        
        string IMigrationMetadata.Id
        {
            get { return "202512101301299_add_MatrixItem_toIssuances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
