// <auto-generated />
namespace PublicSafety.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Modified_Items : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modified_Items));
        
        string IMigrationMetadata.Id
        {
            get { return "202511300738335_Modified_Items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
