// <auto-generated />
namespace PublicSafety.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class make_EndDate_null_Jobtitlehistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_EndDate_null_Jobtitlehistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202512120858070_make_EndDate_null_Jobtitlehistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
