// <auto-generated />
namespace PublicSafety.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class remove_dates_jobtitles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_dates_jobtitles));
        
        string IMigrationMetadata.Id
        {
            get { return "202601240642451_remove_dates_jobtitles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
